[package]
name = "synthizer-sys"
version = "0.1.0"
authors = ["Austin Hicks <ahicks@ahicks.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
